config/routes.rb
YouPM::Application.routes.draw do
  get "admin" => "admin#index"

  resources :rentbills do
    resources :rentbill_line_items
  end

  #controller :messages do
  #  get "messages" => "messages#index"
  #  get "new" => :new
  #end
  resources :messages

  controller :sessions do
    get "login" => :new
    post "login" => :create
    delete "logout" => :destroy
  end

  resources :work_assignments

  resources :vendors

  resources :property_assets

  resources :property_units

  resources :managers

  get "index/index"

  root to: 'index#index'

  # Test routes for showing bootstrap design suggestions
  get "signup" => "managers#signup"
  get "confirm" => "managers#confirmemail"

  get "portfolio" => "managers#portfolio"

  resources :properties

  resources :ads
  
  get "repost" => "ads#repost"
  
  resources :activities
  
  resources :tenants

  resources :bills

  resources :workorders

  get "completedorder" => "workorders#markcomplete"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :manager
  after_initialize :init

  validates :manager_id, :presence => true
  
  def init
    self.date = Time.now()
    #self.manager_id = session[:manager_id]
  end
  
end

app/models/ad.rb
class Ad < ActiveRecord::Base
  belongs_to :property_unit
end

app/models/manager.rb
class Manager < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  has_secure_password

  has_many :property
  has_many :activity
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates_presence_of :sender
  validates_presence_of :receiver
end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :manager
  has_many :property_unit
end

app/models/property_asset.rb
class PropertyAsset < ActiveRecord::Base
end

app/models/property_unit.rb
class PropertyUnit < ActiveRecord::Base
  belongs_to :property
  has_many :work_assignment
  has_one :tenant
  has_many :ad
end

app/models/rentbill.rb
class Rentbill < ActiveRecord::Base
  has_many :rentbill_line_items, :dependent => :destroy
  
  validates_presence_of :bill_date
  validates_presence_of :tenant_id
  
  accepts_nested_attributes_for :rentbill_line_items, :reject_if => :all_blank, :allow_destroy => true  
end

app/models/tenant.rb
class Tenant < ActiveRecord::Base
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
end

app/models/work_assignment.rb
class WorkAssignment < ActiveRecord::Base
  belongs_to :property_units
end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  skip_before_filter :authorize, only: [:create, :new]
  # GET /managers
  # GET /managers.json
  def index
    @managers = Manager.order(:email)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @managers }
    end
  end

  # GET /managers/1
  # GET /managers/1.json
  def show
    @manager = Manager.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @manager }
    end
  end

  # GET /managers/new
  # GET /managers/new.json
  def new
    @manager = Manager.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @manager }
    end
  end

  # GET /managers/1/edit
  def edit
    @manager = Manager.find(params[:id])
  end

  # POST /managers
  # POST /managers.json
  def create
    @manager = Manager.new(params[:manager])

    respond_to do |format|
      if @manager.save
        format.html { redirect_to '/', 
          notice: 'Manager #{@manager.email} was successfully created.' }
        format.json { render json: @manager, status: :created, location: @manager }
      else
        format.html { render action: "new" }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /managers/1
  # PUT /managers/1.json
  def update
    @manager = Manager.find(params[:id])

    respond_to do |format|
      if @manager.update_attributes(params[:manager])
        format.html { redirect_to :action => 'index', notice: 'Manager was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /managers/1
  # DELETE /managers/1.json
  def destroy
    @manager = Manager.find(params[:id])
    begin
      @manager.destroy
      flash[:notice] = "#{@manager.email} deleted"
    rescue Exception => e
      flash[:notice] = e.message
    end

    respond_to do |format|
      format.html { redirect_to managers_url }
      format.json { head :ok }
    end
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/rentbills_helper.rb
module RentbillsHelper

  def setup_rentbill(rentbill)
    rentbill.rentbill_line_items.build
    rentbill
  end

  def add_rentbill_line_item_link(name, form)
    link_to_function name do |page|
      line_item = render(:partial => 'line_item', :locals => { :pf => form, :line_item => Rentbill_line_item.new })
    #  page << %{
    #    var new_line_item_id = "new_" + new Date().getTime();
    #    $('line_items').insert({ bottom: "#{ escape_javascript line_item }".replace(/new_\\d+/g, new_line_item_id) });
    #  }
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/managers/_form.html.haml
= form_for @manager do |f|
  -if @manager.errors.any?
    #error_explanation
      %h2= "#{pluralize(@manager.errors.count, "error")} prohibited this manager from being saved:"
      %ul
        - @manager.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :password, 'Password'
    = f.password_field :password
  .field
    = f.label :password_confirmation, 'Confirm Password' 
    = f.password_field :password_confirmation 
  .field
    = f.label :lastname
    = f.text_field :lastname
  .field
    = f.label :firstname
    = f.text_field :firstname
  .field
    = f.label :phonenumber
    = f.text_field :phonenumber
  .field
    = f.label :city
    = f.text_field :city
  .field
    = f.label :state
    = f.text_field :state
  .field
    = f.label :zip
    = f.text_field :zip
  .field
    = f.label :streetaddress
    = f.text_field :streetaddress
  .actions
    = f.submit 'Save'

app/views/managers/edit.html.haml
%h1 Editing manager

= render 'form'

= link_to 'Show', @manager
\|
= link_to 'Back', managers_path

app/views/managers/index.html.haml
%h1 Listing managers

- if notice
  %p{:id=>"notice"}= notice 

%table
  %tr
    %th Email
    /   %th Password Digest
    %th Lastname
    %th Firstname
    %th Phonenumber
    %th City
    %th State
    %th Zip
    %th Street
    %th
    %th
    %th

  - @managers.each do |manager|
    %tr
      %td= manager.email
      /      %td= manager.password_digest
      %td= manager.lastname
      %td= manager.firstname
      %td= manager.phonenumber
      %td= manager.city
      %td= manager.state
      %td= manager.zip
      %td= manager.streetaddress
      %td= link_to 'Show', manager
      %td= link_to 'Edit', edit_manager_path(manager)
      %td= link_to 'Destroy', manager, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Manager', new_manager_path

app/views/managers/new.html.haml
%h1 New manager

= render 'form'

= link_to 'Back', managers_path

app/views/managers/show.html.haml
%p#notice= notice

%p
  %b Email:
  = @manager.email
%p
  %b Password Digest:
  = @manager.password_digest
%p
  %b Lastname:
  = @manager.lastname
%p
  %b Firstname:
  = @manager.firstname
%p
  %b Phonenumber:
  = @manager.phonenumber
%p
  %b City:
  = @manager.city
%p
  %b State:
  = @manager.state
%p
  %b Zip:
  = @manager.zip
%p
  %b Street:
  = @manager.streetaddress

= link_to 'Edit', edit_manager_path(@manager)
\|
= link_to 'Back', managers_path