config/routes.rb
YouPM::Application.routes.draw do
  get "admin" => "admin#index"

  resources :rentbills do
    resources :rentbill_line_items
  end

  #controller :messages do
  #  get "messages" => "messages#index"
  #  get "new" => :new
  #end
  resources :messages

  controller :sessions do
    get "login" => :new
    post "login" => :create
    delete "logout" => :destroy
  end

  resources :work_assignments

  resources :vendors

  resources :property_assets

  resources :property_units

  resources :managers

  get "index/index"

  root to: 'index#index'

  # Test routes for showing bootstrap design suggestions
  get "signup" => "managers#signup"
  get "confirm" => "managers#confirmemail"

  get "portfolio" => "managers#portfolio"

  resources :properties

  resources :ads
  
  get "repost" => "ads#repost"
  
  resources :activities
  
  resources :tenants

  resources :bills

  resources :workorders

  get "completedorder" => "workorders#markcomplete"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :manager
  after_initialize :init

  validates :manager_id, :presence => true
  
  def init
    self.date = Time.now()
    #self.manager_id = session[:manager_id]
  end
  
end

app/models/ad.rb
class Ad < ActiveRecord::Base
  belongs_to :property_unit
end

app/models/manager.rb
class Manager < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  has_secure_password

  has_many :property
  has_many :activity
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates_presence_of :sender
  validates_presence_of :receiver
end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :manager
  has_many :property_unit
end

app/models/property_asset.rb
class PropertyAsset < ActiveRecord::Base
end

app/models/property_unit.rb
class PropertyUnit < ActiveRecord::Base
  belongs_to :property
  has_many :work_assignment
  has_one :tenant
  has_many :ad
end

app/models/rentbill.rb
class Rentbill < ActiveRecord::Base
  has_many :rentbill_line_items, :dependent => :destroy
  
  validates_presence_of :bill_date
  validates_presence_of :tenant_id
  
  accepts_nested_attributes_for :rentbill_line_items, :reject_if => :all_blank, :allow_destroy => true  
end

app/models/tenant.rb
class Tenant < ActiveRecord::Base
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
end

app/models/work_assignment.rb
class WorkAssignment < ActiveRecord::Base
  belongs_to :property_units
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.where(:manager_id=>session[:manager_id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @properties }
    end
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    @property = Property.where(:id => params[:id], :manager_id => session[:manager_id]).first
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @property }
    end
  end

  # GET /properties/new
  # GET /properties/new.json
  def new
    @property = Property.new
    #@property[:manager_id] = session[:manager_id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @property }
    end
  end

  # GET /properties/1/edit
  def edit
    @property = Property.find_by_id_and_manager_id(params[:id], session[:manager_id])
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(params[:property])
    @property[:manager_id] = session[:manager_id]

    @act = Activity.create(
		 :description => "Added new property " + @property[:name],
		 :url => properties_url,
		 :urgency => 0)
    @act.save

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render json: @property, status: :created, location: @property }
      else
        format.html { render action: "new" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /properties/1
  # PUT /properties/1.json
  def update
    @property = Property.find_by_id_and_manager_id(params[:id], session[:manager_id])

    respond_to do |format|
      if @property.update_attributes(params[:property])
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property = Property.find_by_id_and_manager_id(params[:id], session[:manager_id])
    @property.destroy

    respond_to do |format|
      format.html { redirect_to properties_url }
      format.json { head :ok }
    end
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/rentbills_helper.rb
module RentbillsHelper

  def setup_rentbill(rentbill)
    rentbill.rentbill_line_items.build
    rentbill
  end

  def add_rentbill_line_item_link(name, form)
    link_to_function name do |page|
      line_item = render(:partial => 'line_item', :locals => { :pf => form, :line_item => Rentbill_line_item.new })
    #  page << %{
    #    var new_line_item_id = "new_" + new Date().getTime();
    #    $('line_items').insert({ bottom: "#{ escape_javascript line_item }".replace(/new_\\d+/g, new_line_item_id) });
    #  }
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/properties/_form.html.haml
= form_for @property do |f|
  -if @property.errors.any?
    #error_explanation
      %h2= "#{pluralize(@property.errors.count, "error")} prohibited this property from being saved:"
      %ul
        - @property.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :headline
    = f.text_area :headline
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :streetaddress
    = f.text_field :streetaddress
  .field
    = f.label :zipcode
    = f.text_field :zipcode
  .field
    = f.label :city
    = f.text_field :city
  .field
    = f.label :state
    = f.text_field :state
  .field
    = f.label :country
    = f.text_field :country
  .field
    = f.label :longitude
    = f.text_field :longitude
  .field
    = f.label :latitude
    = f.text_field :latitude
  .field
    = f.label :type
    = f.number_field :type
  .field
    = f.label :year_built
    = f.text_field :year_built
  .field
    = f.label :stories
    = f.text_field :stories
  .actions
    = f.submit 'Save'

app/views/properties/edit.html.haml
%h1 Editing property

= render 'form'

= link_to 'Show', @property
\|
= link_to 'Back', properties_path

app/views/properties/index.html.haml
%h1 Listing properties

%table
  %tr
    %th Name
    %th Headline
    %th Description
    %th Streetaddress
    %th Zipcode
    %th City
    %th State
    %th Country
    %th Longitude
    %th Latitude
    %th Type
    %th Year built
    %th Stories
    %th
    %th
    %th

  - @properties.each do |property|
    %tr
      %td= property.name
      %td= property.headline
      %td= property.description
      %td= property.streetaddress
      %td= property.zipcode
      %td= property.city
      %td= property.state
      %td= property.country
      %td= property.longitude
      %td= property.latitude
      %td= property.type
      %td= property.year_built
      %td= property.stories
      %td= link_to 'Show', property
      %td= link_to 'Edit', edit_property_path(property)
      %td= link_to 'Destroy', property, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Property', new_property_path

app/views/properties/new.html.haml
%h1 New property

= render 'form'

= link_to 'Back', properties_path

app/views/properties/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @property.name
%p
  %b Headline:
  = @property.headline
%p
  %b Description:
  = @property.description
%p
  %b Streetaddress:
  = @property.streetaddress
%p
  %b Zipcode:
  = @property.zipcode
%p
  %b City:
  = @property.city
%p
  %b State:
  = @property.state
%p
  %b Country:
  = @property.country
%p
  %b Longitude:
  = @property.longitude
%p
  %b Latitude:
  = @property.latitude
%p
  %b Type:
  = @property.type
%p
  %b Year built:
  = @property.year_built
%p
  %b Stories:
  = @property.stories

= link_to 'Edit', edit_property_path(@property)
\|
= link_to 'Back', properties_path