config/routes.rb
YouPM::Application.routes.draw do
  get "admin" => "admin#index"

  resources :rentbills do
    resources :rentbill_line_items
  end

  #controller :messages do
  #  get "messages" => "messages#index"
  #  get "new" => :new
  #end
  resources :messages

  controller :sessions do
    get "login" => :new
    post "login" => :create
    delete "logout" => :destroy
  end

  resources :work_assignments

  resources :vendors

  resources :property_assets

  resources :property_units

  resources :managers

  get "index/index"

  root to: 'index#index'

  # Test routes for showing bootstrap design suggestions
  get "signup" => "managers#signup"
  get "confirm" => "managers#confirmemail"

  get "portfolio" => "managers#portfolio"

  resources :properties

  resources :ads
  
  get "repost" => "ads#repost"
  
  resources :activities
  
  resources :tenants

  resources :bills

  resources :workorders

  get "completedorder" => "workorders#markcomplete"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :manager
  after_initialize :init

  validates :manager_id, :presence => true
  
  def init
    self.date = Time.now()
    #self.manager_id = session[:manager_id]
  end
  
end

app/models/ad.rb
class Ad < ActiveRecord::Base
  belongs_to :property_unit
end

app/models/manager.rb
class Manager < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  has_secure_password

  has_many :property
  has_many :activity
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates_presence_of :sender
  validates_presence_of :receiver
end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :manager
  has_many :property_unit
end

app/models/property_asset.rb
class PropertyAsset < ActiveRecord::Base
end

app/models/property_unit.rb
class PropertyUnit < ActiveRecord::Base
  belongs_to :property
  has_many :work_assignment
  has_one :tenant
  has_many :ad
end

app/models/rentbill.rb
class Rentbill < ActiveRecord::Base
  has_many :rentbill_line_items, :dependent => :destroy
  
  validates_presence_of :bill_date
  validates_presence_of :tenant_id
  
  accepts_nested_attributes_for :rentbill_line_items, :reject_if => :all_blank, :allow_destroy => true  
end

app/models/tenant.rb
class Tenant < ActiveRecord::Base
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
end

app/models/work_assignment.rb
class WorkAssignment < ActiveRecord::Base
  belongs_to :property_units
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  # GET /vendors
  # GET /vendors.json
  def index
    @vendors = Vendor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vendors }
    end
  end

  # GET /vendors/1
  # GET /vendors/1.json
  def show
    @vendor = Vendor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vendor }
    end
  end

  # GET /vendors/new
  # GET /vendors/new.json
  def new
    @vendor = Vendor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vendor }
    end
  end

  # GET /vendors/1/edit
  def edit
    @vendor = Vendor.find(params[:id])
  end

  # POST /vendors
  # POST /vendors.json
  def create
    @vendor = Vendor.new(params[:vendor])

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to @vendor, notice: 'Vendor was successfully created.' }
        format.json { render json: @vendor, status: :created, location: @vendor }
      else
        format.html { render action: "new" }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vendors/1
  # PUT /vendors/1.json
  def update
    @vendor = Vendor.find(params[:id])

    respond_to do |format|
      if @vendor.update_attributes(params[:vendor])
        format.html { redirect_to @vendor, notice: 'Vendor was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1
  # DELETE /vendors/1.json
  def destroy
    @vendor = Vendor.find(params[:id])
    @vendor.destroy

    respond_to do |format|
      format.html { redirect_to vendors_url }
      format.json { head :ok }
    end
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/rentbills_helper.rb
module RentbillsHelper

  def setup_rentbill(rentbill)
    rentbill.rentbill_line_items.build
    rentbill
  end

  def add_rentbill_line_item_link(name, form)
    link_to_function name do |page|
      line_item = render(:partial => 'line_item', :locals => { :pf => form, :line_item => Rentbill_line_item.new })
    #  page << %{
    #    var new_line_item_id = "new_" + new Date().getTime();
    #    $('line_items').insert({ bottom: "#{ escape_javascript line_item }".replace(/new_\\d+/g, new_line_item_id) });
    #  }
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/_form.html.haml
= form_for @vendor do |f|
  -if @vendor.errors.any?
    #error_explanation
      %h2= "#{pluralize(@vendor.errors.count, "error")} prohibited this vendor from being saved:"
      %ul
        - @vendor.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :company_name
    = f.text_field :company_name
  .field
    = f.label :streetaddress
    = f.text_field :streetaddress
  .field
    = f.label :phone_number
    = f.text_field :phone_number
  .field
    = f.label :phone_mobile
    = f.text_field :phone_mobile
  .field
    = f.label :phone_emergency
    = f.text_field :phone_emergency
  .field
    = f.label :fax_number
    = f.text_field :fax_number
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :website
    = f.text_field :website
  .field
    = f.label :contact_person
    = f.text_field :contact_person
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :services
    = f.text_area :services
  .field
    = f.label :vendor_type
    = f.text_field :vendor_type
  .actions
    = f.submit 'Save'

app/views/vendors/edit.html.haml
%h1 Editing vendor

= render 'form'

= link_to 'Show', @vendor
\|
= link_to 'Back', vendors_path

app/views/vendors/index.html.haml
%h1 Listing vendors

%table
  %tr
    %th Company name
    %th Streetaddress
    %th Phone number
    %th Phone mobile
    %th Phone emergency
    %th Fax number
    %th Email
    %th Website
    %th Contact person
    %th Description
    %th Services
    %th Vendor type
    %th
    %th
    %th

  - @vendors.each do |vendor|
    %tr
      %td= vendor.company_name
      %td= vendor.streetaddress
      %td= vendor.phone_number
      %td= vendor.phone_mobile
      %td= vendor.phone_emergency
      %td= vendor.fax_number
      %td= vendor.email
      %td= vendor.website
      %td= vendor.contact_person
      %td= vendor.description
      %td= vendor.services
      %td= vendor.vendor_type
      %td= link_to 'Show', vendor
      %td= link_to 'Edit', edit_vendor_path(vendor)
      %td= link_to 'Destroy', vendor, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Vendor', new_vendor_path

app/views/vendors/new.html.haml
%h1 New vendor

= render 'form'

= link_to 'Back', vendors_path

app/views/vendors/show.html.haml
%p#notice= notice

%p
  %b Company name:
  = @vendor.company_name
%p
  %b Streetaddress:
  = @vendor.streetaddress
%p
  %b Phone number:
  = @vendor.phone_number
%p
  %b Phone mobile:
  = @vendor.phone_mobile
%p
  %b Phone emergency:
  = @vendor.phone_emergency
%p
  %b Fax number:
  = @vendor.fax_number
%p
  %b Email:
  = @vendor.email
%p
  %b Website:
  = @vendor.website
%p
  %b Contact person:
  = @vendor.contact_person
%p
  %b Description:
  = @vendor.description
%p
  %b Services:
  = @vendor.services
%p
  %b Vendor type:
  = @vendor.vendor_type

= link_to 'Edit', edit_vendor_path(@vendor)
\|
= link_to 'Back', vendors_path