config/routes.rb
YouPM::Application.routes.draw do
  get "admin" => "admin#index"

  resources :rentbills do
    resources :rentbill_line_items
  end

  #controller :messages do
  #  get "messages" => "messages#index"
  #  get "new" => :new
  #end
  resources :messages

  controller :sessions do
    get "login" => :new
    post "login" => :create
    delete "logout" => :destroy
  end

  resources :work_assignments

  resources :vendors

  resources :property_assets

  resources :property_units

  resources :managers

  get "index/index"

  root to: 'index#index'

  # Test routes for showing bootstrap design suggestions
  get "signup" => "managers#signup"
  get "confirm" => "managers#confirmemail"

  get "portfolio" => "managers#portfolio"

  resources :properties

  resources :ads
  
  get "repost" => "ads#repost"
  
  resources :activities
  
  resources :tenants

  resources :bills

  resources :workorders

  get "completedorder" => "workorders#markcomplete"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :manager
  after_initialize :init

  validates :manager_id, :presence => true
  
  def init
    self.date = Time.now()
    #self.manager_id = session[:manager_id]
  end
  
end

app/models/ad.rb
class Ad < ActiveRecord::Base
  belongs_to :property_unit
end

app/models/manager.rb
class Manager < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  has_secure_password

  has_many :property
  has_many :activity
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates_presence_of :sender
  validates_presence_of :receiver
end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :manager
  has_many :property_unit
end

app/models/property_asset.rb
class PropertyAsset < ActiveRecord::Base
end

app/models/property_unit.rb
class PropertyUnit < ActiveRecord::Base
  belongs_to :property
  has_many :work_assignment
  has_one :tenant
  has_many :ad
end

app/models/rentbill.rb
class Rentbill < ActiveRecord::Base
  has_many :rentbill_line_items, :dependent => :destroy
  
  validates_presence_of :bill_date
  validates_presence_of :tenant_id
  
  accepts_nested_attributes_for :rentbill_line_items, :reject_if => :all_blank, :allow_destroy => true  
end

app/models/tenant.rb
class Tenant < ActiveRecord::Base
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
end

app/models/work_assignment.rb
class WorkAssignment < ActiveRecord::Base
  belongs_to :property_units
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.where(:manager_id => session[:manager_id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @activities }
    end
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    @activity = Activity.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/new
  # GET /activities/new.json
  def new
    @activity = Activity.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/1/edit
  #def edit
  #  @activity = Activity.find(params[:id])
  #end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(params[:activity])

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render json: @activity, status: :created, location: @activity }
      else
        format.html { render action: "new" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /activities/1
  # PUT /activities/1.json
  def update
    @activity = Activity.find(params[:id])

    respond_to do |format|
      if @activity.update_attributes(params[:activity])
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to activities_url }
      format.json { head :ok }
    end
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/rentbills_helper.rb
module RentbillsHelper

  def setup_rentbill(rentbill)
    rentbill.rentbill_line_items.build
    rentbill
  end

  def add_rentbill_line_item_link(name, form)
    link_to_function name do |page|
      line_item = render(:partial => 'line_item', :locals => { :pf => form, :line_item => Rentbill_line_item.new })
    #  page << %{
    #    var new_line_item_id = "new_" + new Date().getTime();
    #    $('line_items').insert({ bottom: "#{ escape_javascript line_item }".replace(/new_\\d+/g, new_line_item_id) });
    #  }
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/activities/_form.html.haml
= form_for @activity do |f|
  -if @activity.errors.any?
    #error_explanation
      %h2= "#{pluralize(@activity.errors.count, "error")} prohibited this activity from being saved:"
      %ul
        - @activity.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :date
    = f.date_select :date
  .field
    = f.label :url
    = f.text_field :url
  .field
    = f.label :urgency
    = f.text_field :urgency
  .actions
    = f.submit 'Save'

app/views/activities/edit.html.haml
%h1 Editing activity

= render 'form'

= link_to 'Show', @activity
\|
= link_to 'Back', activities_path

app/views/activities/index.html.haml
%h1 Listing activities

%table
  %tr
    %th Description
    %th Date
    %th Url
    %th Urgency
    %th Tag
    %th
    %th
    %th

  - @activities.each do |activity|
    %tr
      %td= activity.description
      %td= activity.date
      %td= activity.url
      %td= activity.urgency
      %td= activity.tag
      %td= link_to 'Show', activity
      %td= link_to 'Edit', edit_activity_path(activity)
      %td= link_to 'Destroy', activity, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Activity', new_activity_path

app/views/activities/new.html.haml
%h1 New activity

= render 'form'

= link_to 'Back', activities_path

app/views/activities/show.html.haml
%p#notice= notice

%p
  %b Description:
  = @activity.description
%p
  %b Date:
  = @activity.date
%p
  %b Url:
  = @activity.url
%p
  %b Urgency:
  = @activity.urgency

= link_to 'Edit', edit_activity_path(@activity)
\|
= link_to 'Back', activities_path